import { useSyncExternalStore } from 'react';
export type Language = 'ar' | 'en';
let language: Language = 'ar';
const listeners = new Set<() => void>();
export function setLanguage(next: Language) { language = next; document.documentElement.lang = next; document.documentElement.dir = next === 'ar' ? 'rtl' : 'ltr'; listeners.forEach(fn => fn()); }
export function useLanguage() { return useSyncExternalStore(fn => { listeners.add(fn); return () => { listeners.delete(fn); }; }, () => language); }
export function locale() { return language === 'ar' ? 'ar-SY' : 'en-US'; }
export const english: Record<string, string> = {
  'متصل':'Online','غير متصل':'Offline','تنبيه':'Warning','موقوف':'Disabled','نظرة عامة':'Overview','الأجهزة':'Devices','المشاريع':'Projects','القياسات':'Telemetry','التنبيهات':'Alerts','دليل الربط':'Connection guide','الإعدادات':'Settings','بيئة التطوير':'Development environment','بيئة البرمجة':'Code studio',
  'بانتظار أول قراءة':'Awaiting first reading','الآن':'Now','إغلاق':'Close','قراءة':'reading','تعذّر قراءة البيانات المحلية.':'Could not read local data.','شغّل تطبيق وصل من ملفه التنفيذي؛ هذه الواجهة مخصصة لبرنامج سطح المكتب.':'Launch the Wasl executable. This interface requires the desktop application.',
  'تم النسخ إلى الحافظة.':'Copied to clipboard.','حدد النص وانسخه باستخدام Ctrl+C.':'Select the text and press Ctrl+C to copy.','تم إيقاف المفتاح. يمكنك إصدار مفتاح جديد لاحقاً.':'Key disabled. You can generate a new key later.','تم تصدير قائمة الأجهزة.':'Device list exported.','تم حفظ إعدادات مستقبل البيانات.':'Receiver settings saved.',
  'وصل':'Wasl','سطح المكتب':'DESKTOP','مساحة العمل المحلية':'Local workspace','الإصدار المجتمعي · مفتوحة المصدر':'Community edition · Open source','مساحة العمل':'WORKSPACE','التطوير والإدارة':'DEVELOP & MANAGE','تقنية نصنعها معاً.':'Built to be yours.','مفتوحة المصدر. تعمل محلياً.':'Open source. Runs locally.','بياناتك على جهازك.':'Your data, on your computer.','تعرّف على وصل':'Explore Wasl','لا تحتاج إلى حساب سحابي':'No cloud account required','يعمل على جهازك':'Runs locally','استقبال البيانات مفعّل':'Receiver ready','استقبال البيانات غير متاح':'Receiver unavailable',
  'عالمك المتصل، بين يديك':'YOUR CONNECTED WORLD','نظرة على مساحة عملك':'Workspace overview','أجهزتك وبياناتك ومشاريعك، في مكان واحد.':'Your devices, data, and projects, together.','أضف أجهزتك وتابع أحدث قراءاتها.':'Register hardware and follow its latest readings.','من أول نموذج تجريبي إلى خط الإنتاج.':'From the first prototype to the factory floor.','تابع الإشارات القادمة من أجهزتك.':'Follow signals from your connected devices.','الأجهزة التي تحتاج إلى انتباهك.':'Devices that need your attention.','إعدادات الاستقبال والبيانات المحلية.':'Language, receiver, and local data settings.','تعرّف على طريقة توصيل جهازك ببرنامج وصل.':'Make your first connection to Wasl.',
  'انتقل إلى أجهزتي لتصدير الأجهزة الفعلية':'Switch to My devices to export your registered hardware','حفظ ملف CSV':'Save CSV','تصدير':'Export','إضافة جهاز':'Add device','مصدر البيانات':'Data source','أجهزتي':'My devices','بيانات تجريبية':'Demo workspace','بيانات توضيحية للتجربة، وليست قراءات من أجهزة حقيقية.':'Explore sample readings; no real hardware is connected here.','تُحفظ البيانات محلياً ويُحدَّث العرض كل ٣ ثوانٍ.':'Stored locally. Refreshed every 3 seconds.','إعادة المحاولة':'Retry','فتح الإعدادات':'Open settings',
  'إجمالي الأجهزة':'Total devices','الأجهزة المتصلة':'Devices online','بانتظار أول اتصال':'Ready for your first connection','القراءات المحفوظة':'Stored measurements','قراءات توضيحية للتجربة':'Sample measurements','آخر ٥٠٬٠٠٠ قراءة كحد أقصى':'Latest 50,000 measurements retained','التنبيهات النشطة':'Active alerts','أجهزة تحتاج إلى متابعة':'Devices need attention','لا توجد تنبيهات حالياً':'No active alerts','القراءات الواردة':'Telemetry activity','تجريبي':'Demo','محلي':'Local','عدد القراءات المستقبلة خلال الفترة المحددة':'Measurements received during the selected period','ساعة':'1h','يوم':'24h','أسبوع':'7d','القراءات':'Measurements','بتوقيت هذا الكمبيوتر':'Computer local time','استكشف دون توصيل جهاز':'Explore without hardware','استقبال HTTP بمفتاح خاص لكل جهاز':'HTTP ingestion with per-device keys','استعراض القياسات':'View telemetry','حالة الأجهزة':'Device health','نظرة سريعة على شبكتك':'Your fleet at a glance','/ موقوف':'/ Disabled',
  'عرض جميع الأجهزة':'View all devices','حالة الجهاز':'Device status','الكل':'All','البحث عن جهاز':'Search devices','ابحث عن جهاز...':'Search devices...','تصفية حسب المشروع':'Filter by project','كل المشاريع':'All projects','الجهاز':'Device','الحالة':'Status','المشروع':'Project','آخر قراءة':'Latest reading','آخر اتصال':'Last activity','لم نعثر على أجهزة مطابقة':'No matching devices','أول اتصال يبدأ من هنا':'Your first connection starts here','جرّب اسماً آخر أو غيّر خيارات التصفية.':'Try a different name or filter.','أضف جهازك واحصل على مفتاح لبدء إرسال القياسات.':'Register hardware and get a key to send measurements.','إضافة أول جهاز':'Add your first device','عرض':'Showing','من':'of','أجهزة':'devices','مساحة تجريبية':'Sample workspace','SQLite · تخزين محلي':'SQLite · Local storage','مشاريعك':'Your projects','مشروعك الأول بانتظارك':'Your first project awaits','أدخل اسم المشروع عند تسجيل جهاز جديد.':'Enter a project name when registering a device.',
  'تنبيهات مساحة العمل':'Workspace alerts','أمثلة توضيحية لتنبيهات الأجهزة':'Illustrative sample alerts','يظهر تنبيه عندما يتوقف جهاز سبق له الاتصال عن الإرسال لمدة ٥ دقائق.':'An alert appears when a previously connected device stops reporting for 5 minutes.','تفاصيل الجهاز':'Device details','كل شيء على ما يرام':'All clear','لا توجد أجهزة انقطع اتصالها حالياً.':'No previously connected devices are currently offline.','أحدث القراءات':'Latest measurements','أحدث قراءة من كل جهاز':'Most recent reading per device','أضف جهازاً وأرسل أول قراءة لبدء المتابعة.':'Register a device and send a reading to begin.',
  'دليل المطوّر / وصل':'WASL / DEVELOPER DOCS','اربط أول جهاز بخطوات بسيطة.':'Connect your first device.','وصل برنامج محلي للمهندسين الكهربائيين وشركات الإلكترونيات والمختبرات الجامعية والمصانع ومطوّري إنترنت الأشياء.':'Wasl is a local workspace for electrical engineers, electronics companies, university labs, manufacturers, and IoT developers.','١':'1','٢':'2','٣':'3','٤':'4','أضف جهازك':'Register your hardware','اضغط «إضافة جهاز»، ثم أدخل اسمه ونوع اللوحة والمشروع والموقع. انسخ مفتاح الوصول الذي سيظهر مرة واحدة.':'Choose Add device, enter a name, board, project, and location, then copy the one-time access key.','جهّز الاتصال':'Prepare the connection','للتجربة من هذا الكمبيوتر، استخدم العنوان المحلي. لربط ESP32 أو لوحة على نفس الشبكة، فعّل «الشبكة المحلية» في الإعدادات، ثم استخدم عنوان الكمبيوتر. أبقِ وصل مفتوحاً أثناء استقبال القراءات.':'Use the loopback address on this computer. For an ESP32 or another board, enable LAN access in Settings and use this computer’s LAN address. Keep Wasl open to receive data.','نسخ عنوان الاستقبال':'Copy receiver URL','أرسل أول قراءة':'Send a reading','استبدل':'Replace','بمفتاح جهازك. على Windows استخدم':'with your device key. On Windows use','في PowerShell.':'in PowerShell.','تابع البيانات':'Follow the data','انتقل إلى «أجهزتي». سيظهر الجهاز متصلاً بعد وصول القراءة، وتتحدث الواجهة كل ٣ ثوانٍ. يمكنك استعراض آخر ١٠٠ قراءة من تفاصيل الجهاز.':'Switch to My devices. The device becomes online after receiving data. The view refreshes every 3 seconds. Device details show the latest 100 readings.','استخدم HTTP على شبكة موثوقة. لربط أجهزة خارج الشبكة تحتاج إلى بوابة HTTPS أو VPN. هذا الإصدار لا يضم وسيط MQTT أو تحديثات OTA أو تحكماً بالمشغلات.':'Use HTTP on a trusted network. Remote devices need an HTTPS or VPN gateway. This release does not include MQTT, OTA, or actuator commands.',
  'مفتوح للجميع.':'Open for everyone.','مرخّص برخصة MIT. يمكنك استخدامه وتعديله ومشاركة تطويرك على GitHub.':'MIT licensed. Use, modify, and share your improvements on GitHub.','في هذا الإصدار':'In this release','واجهة بالعربية والإنجليزية مع دعم اتجاه الكتابة':'Arabic and English interface with RTL support','برنامج Windows وLinux مستقل':'Standalone Windows and Linux app','أجهزة ومشاريع وقراءات محلية':'Local devices, projects, and telemetry','مفاتيح وصول قابلة للتجديد والإيقاف':'Rotatable, revocable device keys','تصدير CSV ونسخة احتياطية SQLite':'CSV export and SQLite backups','تعمل لوحة المتابعة دون إنترنت، والخطوط والملفات اللازمة مضمنة في البرنامج. تتطلب البرمجة تثبيت أدوات اللوحة مرة واحدة أو استيرادها محلياً.':'The dashboard works offline. Fonts and assets are bundled locally.',
  'مستقبل بيانات الأجهزة':'Device data receiver','يستقبل البرنامج القراءات ما دام مفتوحاً. حدّد إعدادات الشبكة ورقم المنفذ.':'The receiver runs while Wasl is open. Choose a connection scope and port.','السماح بالاتصال من الشبكة المحلية':'Allow devices on the local network','لتوصيل اللوحات والأجهزة الموجودة على نفس الشبكة.':'Connect boards and devices on the same network.','منفذ HTTP':'HTTP port','سيسمح هذا الخيار للأجهزة على شبكتك بإرسال القياسات بمفاتيحها. قد تحتاج إلى السماح للتطبيق عبر جدار الحماية. استخدم شبكة خاصة موثوقة.':'Devices on your LAN can send readings using their keys. Your firewall may need a private-network rule. Use a trusted network.','جارٍ الحفظ...':'Saving...','حفظ إعدادات الاستقبال':'Save receiver settings','استقبال البيانات متوقف':'Receiver stopped','نسخ العنوان':'Copy address','بياناتك، على جهازك.':'Your data stays with you.','يحتفظ وصل بآخر ٥٠٬٠٠٠ قراءة في قاعدة بيانات SQLite على جهازك. تُحفظ مفاتيح الوصول بصيغة تجزئة آمنة، ولا تُخزّن كنص صريح.':'Wasl retains the latest 50,000 readings. Devices and hashed access keys are stored in a local SQLite database.','مجلد البيانات':'Data folder','تم حفظ النسخة الاحتياطية. احتفظ بها في مكان آمن.':'Backup saved. Keep it in a safe location.','حفظ نسخة احتياطية':'Save backup','استعادة نسخة احتياطية':'Restore a backup','أغلق وصل، واحتفظ بنسخة من قاعدة البيانات الحالية، ثم استبدل ملف':'Close Wasl, keep a copy of the current database, then replace','في مجلد البيانات بنسختك الاحتياطية وافتح البرنامج من جديد.':'in the data folder with your backup and reopen the app.','وصل — الإصدار المجتمعي':'Wasl — Community edition','وصل · اتصالات مفتوحة، وإمكانات مشتركة.':'Wasl · Open connections. Shared possibilities.','الإصدار المجتمعي':'Community edition',
  'إضافة جهاز جديد':'Add a device','أضف جهازك للحصول على مفتاح وصول خاص به.':'Register hardware to receive a unique access key.','اسم الجهاز':'Device name','مثال: حساس البيت البلاستيكي':'e.g. Greenhouse sensor','نوع اللوحة والحساس':'Board and sensor','مثال: الزراعة الذكية':'e.g. Smart agriculture','الموقع':'Location','مثال: دمشق':'e.g. Damascus','سيبقى الجهاز غير متصل حتى يرسل أول قراءة عبر HTTP.':'The device stays offline until its first HTTP measurement arrives.','جارٍ التسجيل...':'Registering...','تسجيل الجهاز':'Register device','مفتاح جهازك جاهز':'Your device key is ready','انسخ هذا المفتاح الآن. لن يُعرض مجدداً بعد إغلاق النافذة.':'Copy this key now. It will not be shown again after closing.','نسخ المفتاح':'Copy key','المفتاح يسمح بإرسال بيانات هذا الجهاز. لا تنشره في GitHub. يمكنك تجديده أو إيقافه من تفاصيل الجهاز.':'This key allows telemetry for this device. Do not publish it on GitHub. Rotate or revoke it from Device details.','الانتقال إلى أجهزتي':'Go to my devices','البروتوكول':'Protocol','معرّف الجهاز':'Device ID','هذا جهاز تجريبي ببيانات توضيحية. أضف جهازك لجمع قراءات حقيقية.':'This is a sample device. Register your hardware to collect real measurements.','آخر القراءات':'Recent readings','لم تصل أي قراءات بعد. اتبع دليل الربط لإرسال أول قراءة.':'No readings yet. Follow the connection guide to send your first measurement.','تجديد المفتاح':'Rotate key','إيقاف المفتاح':'Revoke key','تجديد مفتاح الوصول':'Rotate access key','إيقاف مفتاح الوصول':'Revoke access key','سيتوقف المفتاح الحالي عن العمل. حدّث برنامج جهازك بالمفتاح الجديد لاستئناف إرسال القياسات.':'The current key will stop working. Update your firmware with the new key to resume sending data.','سيتوقف استقبال القياسات من هذا الجهاز. ستبقى قراءاته محفوظة، ويمكنك إصدار مفتاح جديد لاحقاً.':'Telemetry from this device will stop. Readings stay saved, and you can generate a new key later.','جارٍ التنفيذ...':'Working...','تأكيد':'Confirm','رجوع':'Back','إغلاق الرسالة':'Dismiss message',
  'حساس البيت البلاستيكي':'Greenhouse sensor','مراقب خط الإنتاج':'Production line monitor','عداد الطاقة الشمسية':'Solar energy meter','متحكم خزان المياه':'Water tank controller','حساس بيئة المختبر':'Lab environment sensor','حساس غرفة التبريد':'Cold storage sensor','حساس رطوبة التربة':'Soil moisture sensor','مراقب العاكس الشمسي':'Solar inverter monitor','الزراعة الذكية':'Smart agriculture','مراقبة المصنع':'Factory monitoring','الطاقة الشمسية':'Solar energy','المختبر الجامعي':'University lab','دمشق':'Damascus','حلب':'Aleppo','حمص':'Homs','اللاذقية':'Latakia','مستوى المياه أقل من ٢٠٪':'Water level below 20%','توقف الجهاز عن الإرسال':'Device stopped reporting',
  'تعذّر إتمام العملية.':'The operation could not be completed.','الجهاز غير موجود.':'Device not found.','بيانات الجهاز غير صالحة.':'Invalid device data.','الحد الأقصى لهذا الإصدار هو ١٠٠ جهاز.':'This edition supports up to 100 devices.','الفترة الزمنية غير صالحة.':'Invalid time range.','اختر منفذاً بين ١٠٢٤ و٦٥٥٣٥.':'Choose a port between 1024 and 65535.','المنفذ مستخدم. اختر منفذاً آخر.':'Port in use. Choose another port.','تعذّر حفظ إعدادات الاستقبال. تحقق من المنفذ ومساحة القرص.':'Could not save receiver settings. Check the port and free disk space.','تعذّر تشغيل مستقبل البيانات. اختر منفذاً آخر.':'Could not start the receiver. Choose another port.','تعذّر تشغيل مستقبل البيانات. قد يكون المنفذ ٨٠٨٠ مستخدماً. غيّره من الإعدادات.':'Could not start the receiver. Port 8080 may be in use; change it in Settings.','جارٍ تحديث إعدادات الاستقبال.':'Receiver settings are being updated.',
};
export function t(value: string): string {
  if (language === 'ar') return value;
  const key = value.trim();
  if (english[key] !== undefined) return value.replace(key, english[key]);
  const patterns: [RegExp, (match: RegExpMatchArray) => string][] = [
    [/^منذ (.+) دقيقة$/, m => `${m[1]} minutes ago`], [/^منذ (.+) ساعة$/, m => `${m[1]} hours ago`],
    [/^موزعة على (.+) مشاريع$/, m => `Across ${m[1]} projects`], [/^(.+)٪ من أجهزتك$/, m => `${m[1]}% of your fleet`],
    [/^تفاصيل (.+)$/, m => `Details: ${m[1]}`], [/^يعمل على المنفذ (.+)$/, m => `Listening on port ${m[1]}`],
    [/^(.+): أدخل نصاً من حرف واحد إلى (.+) حرفاً\.$/, m => `${english[m[1]] || m[1]}: enter 1–${m[2]} characters.`],
  ];
  for (const [pattern, replace] of patterns) { const match = key.match(pattern); if (match) return replace(match); }
  return value;
}
export function tr(ar: string, en: string) { return language === 'ar' ? ar : en; }
