import { useCallback, useEffect, useRef, useState } from 'react';
import CodeMirror from '@uiw/react-codemirror';
import { cpp } from '@codemirror/lang-cpp';
import { waslEditor } from './editorTheme';
import { Check, ChevronDown, Code2, Download, FileCode, FolderOpen, Languages, Package, Plus, Radio, RefreshCw, Save, Send, Square, Terminal, Trash2, Upload, X } from 'lucide-react';
import { tr, useLanguage } from './i18n';
import type { IDELog, IDEState, Preferences, Sketch, SketchFile } from './types';

const systemMessages: Record<string, [string, string]> = {
  compileStart: ['بدء التجميع للوحة {board}…', 'Compiling for {board}…'],
  uploadStart: ['تجميع المشروع ورفعه إلى {board}…', 'Compiling and uploading to {board}…'],
  compileSuccess: ['اكتمل التجميع بنجاح.', 'Compilation completed successfully.'],
  uploadSuccess: ['اكتمل رفع البرنامج بنجاح.', 'Upload completed successfully.'],
  failed: ['تعذّرت العملية (رمز الخروج: {code}). راجع المخرجات الأصلية أعلاه.', 'Operation failed (exit code: {code}). See the original output above.'],
  canceled: ['أُلغيت العملية.', 'Operation canceled.'], timeout: ['انتهت المهلة المحددة للعملية.', 'Operation timed out.'],
  refreshed: ['تم تحديث قائمة اللوحات والمنافذ. إذا كانت فارغة، ثبّت حزمة دعم اللوحة أولاً.', 'Boards and ports refreshed. If empty, install a board core first.'],
  saved: ['تم حفظ ملفات المشروع.', 'Sketch files saved.'], newSketch: ['تم إنشاء مشروع جديد.', 'New sketch created.'],
  opened: ['تم فتح المشروع.', 'Sketch opened.'], exported: ['تم تصدير نسخة إلى {path}', 'Sketch copy exported to {path}'],
  installStart: ['تنزيل وتثبيت حزمة {core}… يلزم اتصال بالإنترنت.', 'Downloading and installing {core}… Internet access required.'],
  installSuccess: ['تم تثبيت حزمة دعم اللوحة. حدّث قائمة اللوحات.', 'Board core installed. Refresh the board list.'],
  monitorStart: ['فتح مراقب المنفذ التسلسلي على {port}', 'Opening serial monitor on {port}'],
  monitorStopped: ['أُغلق مراقب المنفذ التسلسلي.', 'Serial monitor closed.'], stopRequested: ['جارٍ إيقاف العملية…', 'Stopping operation…'],
  toolsExported: ['تم تصدير الأدوات إلى {path}', 'Toolchains exported to {path}'],
  toolsImported: ['تم استيراد الأدوات. النسخة السابقة محفوظة في {path}', 'Toolchains imported. Previous tools preserved at {path}'],
  libraryImported: ['تم استيراد مكتبة {name}', 'Library {name} imported.'],
};
function message(log: IDELog, language: 'ar'|'en') {
  if (log.kind === 'raw') return log.text || '';
  let text = systemMessages[log.key || '']?.[language === 'ar' ? 0 : 1] || log.key || '';
  for (const [key, value] of Object.entries(log.values || {})) text = text.replaceAll(`{${key}}`, String(value));
  return text;
}
const friendly: Record<string,[string,string]> = {
  'Stop the current build or serial monitor first':['أوقف التجميع أو مراقب المنفذ التسلسلي أولاً.','Stop the current build or serial monitor first.'],
  'Select a valid board FQBN':['اختر معرّف لوحة صالحاً.','Select a valid board FQBN.'],
  'Select a local serial port':['اختر منفذاً تسلسلياً محلياً صالحاً.','Select a valid local serial port.'],
  'Save the current sketch before creating a new one':['احفظ المشروع الحالي قبل إنشاء مشروع جديد.','Save the current sketch before creating a new one.'],
  'Save the current sketch before opening another':['احفظ المشروع الحالي قبل فتح مشروع آخر.','Save the current sketch before opening another.'],
};
export default function IDE({ active, preferences, onPreferences }: { active:boolean; preferences:Preferences; onPreferences:(value:Preferences)=>Promise<void> }) {
  useLanguage();
  const [state,setState]=useState<IDEState|null>(null), [files,setFiles]=useState<SketchFile[]>([]), [file,setFile]=useState('');
  const [fqbn,setFqbn]=useState('arduino:avr:uno'), [port,setPort]=useState(''), [baud,setBaud]=useState(115200);
  const [pending,setPending]=useState(false), [error,setError]=useState(''), [manager,setManager]=useState(false), [sendText,setSendText]=useState(''), [ending,setEnding]=useState('lf');
  const [newFilename,setNewFilename]=useState(''), [addingFile,setAddingFile]=useState(false), [uploadConfirm,setUploadConfirm]=useState(false);
  const currentFolder=useRef(''), output=useRef<HTMLDivElement>(null), draftChain=useRef(Promise.resolve()), saveRef=useRef(()=>{});
  const adopt=useCallback((sketch:Sketch)=>{setFiles(sketch.files);setFile(sketch.main);currentFolder.current=sketch.folder;},[]);
  const sync=useCallback(async()=>{const next=await window.wasl.ide.state();setState(next);if(currentFolder.current!==next.sketch.folder)adopt(next.sketch);},[adopt]);
  useEffect(()=>{if(!active||!window.wasl)return;sync().catch(e=>setError(e.message));const timer=setInterval(()=>sync().catch(e=>setError(e.message)),500);return()=>clearInterval(timer);},[active,sync]);
  useEffect(()=>{if(output.current)output.current.scrollTop=output.current.scrollHeight;},[state?.logs.length,state?.logs.at(-1)?.id]);
  const locked=pending||!!state?.busy||!!state?.monitoring;
  async function run(action:()=>Promise<unknown>) {setError('');setPending(true);try{await draftChain.current;await action();await sync();}catch(e){const raw=(e as Error).message;const words=friendly[raw];setError(words?tr(words[0],words[1]):raw);}finally{setPending(false);}}
  function change(content:string) { const next=files.map(item=>item.name===file?{...item,content}:item);setFiles(next);draftChain.current=draftChain.current.then(()=>window.wasl.ide.draft(next)).then(()=>{}).catch(e=>{setError(e.message);}); }
  saveRef.current=()=>{if(!locked)run(()=>window.wasl.ide.save(files));};
  useEffect(()=>{const key=(event:KeyboardEvent)=>{if(active&&(event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='s'){event.preventDefault();saveRef.current();}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[active]);
  function addFile(){if(!/^[A-Za-z_][A-Za-z0-9_.-]*\.(ino|h|hpp|cpp|c)$/.test(newFilename)||files.some(f=>f.name===newFilename)){setError(tr('اختر اسماً غير مستخدم بأحرف إنجليزية وامتداد .ino أو .h أو .hpp أو .cpp أو .c.','Choose a unique English filename ending in .ino, .h, .hpp, .cpp, or .c.'));return;}const next=[...files,{name:newFilename,content:'// '+newFilename+'\n'}];setFiles(next);setFile(newFilename);setAddingFile(false);setNewFilename('');draftChain.current=draftChain.current.then(()=>window.wasl.ide.draft(next)).then(()=>{}).catch(e=>setError(e.message));}
  return <div className="ide-workspace">
    <div className="ide-title"><div><h1>{tr('اكتب. جرّب. وصّل.','Write. Test. Connect.')}</h1><p>{tr('اكتب برامج C/C++ وجمّعها وحمّلها إلى لوحتك من مكان واحد.','A local C/C++ workspace, from the first line to your board.')}</p></div><div className="ide-title-actions"><button className="button" onClick={()=>setManager(!manager)}><Package size={17}/>{tr('مدير اللوحات والأدوات','Boards & toolchains')}</button><span className="ide-runtime"><i/>Arduino CLI 1.5.1</span></div></div>
    <div className="ide-toolbar">
      <div className="ide-run-buttons"><button className="verify-button" disabled={locked||!state?.cliAvailable} onClick={()=>run(()=>window.wasl.ide.compile({fqbn,files}))}><Check size={19}/>{tr('تجميع','Verify')}</button><button className="upload-button" disabled={locked||!port||!state?.cliAvailable} onClick={()=>setUploadConfirm(true)}><Upload size={18}/>{tr('رفع','Upload')}</button><button className="stop-button" aria-label={tr('إيقاف','Stop')} disabled={!state?.busy&&!state?.monitoring} onClick={()=>run(()=>window.wasl.ide.stop())}><Square size={15}/></button></div>
      <label className="board-field"><span>{tr('اللوحة','Board')}</span><input list="board-list" value={fqbn} onChange={e=>setFqbn(e.target.value)} disabled={locked} dir="ltr" aria-label={tr('معرّف اللوحة (FQBN)','Board FQBN')}/><datalist id="board-list"><option value="arduino:avr:uno">Arduino Uno</option><option value="arduino:avr:nano:cpu=atmega328">Arduino Nano</option><option value="esp32:esp32:esp32">ESP32 Dev Module</option>{state?.boards.map(board=><option key={board.fqbn} value={board.fqbn}>{board.name}</option>)}</datalist></label>
      <label className="port-field"><span>{tr('المنفذ','Port')}</span><input list="port-list" value={port} onChange={e=>setPort(e.target.value)} disabled={locked} placeholder="COM3 / /dev/ttyUSB0" dir="ltr" aria-label={tr('المنفذ التسلسلي','Serial port')}/><datalist id="port-list">{state?.ports.map(item=><option key={item.port.address} value={item.port.address}>{item.port.label||item.port.address}</option>)}</datalist></label>
      <button className="icon-button" disabled={locked} aria-label={tr('تحديث اللوحات والمنافذ','Refresh boards and ports')} onClick={()=>run(()=>window.wasl.ide.refresh())}><RefreshCw size={17}/></button>
    </div>
    {manager&&<div className="toolchain-manager"><div className="manager-heading"><h2>{tr('أدوات البرمجة والعمل دون إنترنت','Your tools, even offline')}</h2><button className="icon-button" aria-label={tr('إغلاق','Close')} onClick={()=>setManager(false)}><X size={18}/></button></div><p>{tr('أداة Arduino CLI مضمنة في البرنامج. ثبّت حزمة دعم لوحتك مرة واحدة، أو استورد الأدوات من جهاز موثوق يعمل بنظام التشغيل ومعمارية المعالج نفسيهما.','Arduino CLI is bundled. Install a board core once, or import a trusted toolchain bundle from a computer with the same OS and CPU architecture.')}</p><div className="core-grid">{[{id:'arduino:avr',name:'Arduino AVR',boards:'Uno · Nano · Mega'},{id:'esp32:esp32',name:'Espressif ESP32',boards:'ESP32 · ESP32-S3 · ESP32-C3'}].map(core=><div className="core-card" key={core.id}><CpuIcon/><div><b>{core.name}</b><small>{core.boards}</small><span>{state?.cores.find(c=>c.id===core.id)?.installed||tr('غير مثبت','Not installed')}</span></div><button className="button" disabled={locked} onClick={()=>run(()=>window.wasl.ide.installCore(core.id))}><Download size={15}/>{tr('تثبيت عبر الإنترنت','Install online')}</button></div>)}</div><div className="offline-tools"><button className="button" disabled={locked} onClick={()=>run(()=>window.wasl.ide.importTools())}><FolderOpen size={16}/>{tr('استيراد أدوات محلية','Import offline bundle')}</button><button className="button" disabled={locked} onClick={()=>run(()=>window.wasl.ide.exportTools())}><Upload size={16}/>{tr('تصدير الأدوات','Export toolchains')}</button><button className="button" disabled={locked} onClick={()=>run(()=>window.wasl.ide.addLibrary())}><Plus size={16}/>{tr('استيراد مكتبة محلية','Import local library')}</button></div><p className="muted">{tr('حزم دعم اللوحات تحتوي على برامج تنفيذية. استخدم المصادر التي تثق بها فقط. التنزيل من الإنترنت يعتمد على إمكانية الوصول إلى خوادم المورّد.','Board packages contain executables. Use trusted sources only. Online installation depends on reaching the vendor’s servers.')}</p></div>}
    {error&&<div className="error" role="alert">{error}<button className="icon-button" aria-label={tr('إغلاق','Close')} onClick={()=>setError('')}><X size={17}/></button></div>}
    {!state?.cliAvailable&&state&&<div className="warning-banner">{tr('أداة Arduino CLI غير موجودة في هذه النسخة. راجع تعليمات البناء.','Arduino CLI is missing from this build. See the build instructions.')}</div>}
    <div className="code-surface" dir="ltr"><div className="code-titlebar"><span><FileCode size={17}/>{state?.sketch.name||'Sketch'}</span><div><button title={tr('مشروع جديد','New sketch')} disabled={locked} onClick={()=>run(async()=>adopt(await window.wasl.ide.newSketch()))}><Plus size={16}/></button><button title={tr('فتح مشروع','Open sketch')} disabled={locked} onClick={()=>run(async()=>{const sketch=await window.wasl.ide.open();if(sketch)adopt(sketch);})}><FolderOpen size={16}/></button><button title={tr('حفظ المشروع — Ctrl+S','Save sketch — Ctrl+S')} disabled={locked} onClick={()=>run(()=>window.wasl.ide.save(files))}><Save size={16}/></button><button title={tr('تصدير نسخة من المشروع','Export sketch copy')} disabled={locked} onClick={()=>run(()=>window.wasl.ide.exportSketch())}><Upload size={16}/></button></div></div><div className="file-tabs">{files.map(item=><button key={item.name} className={item.name===file?'selected':''} onClick={()=>setFile(item.name)}><Code2 size={14}/>{item.name}{item.name===state?.sketch.main&&state?.dirty&&<i/>}</button>)}<button title={tr('إضافة ملف','Add file')} disabled={locked} onClick={()=>setAddingFile(!addingFile)}><Plus size={15}/></button></div>{addingFile&&<div className="add-file"><input aria-label={tr('اسم الملف الجديد','New filename')} placeholder="sensor.h" value={newFilename} onChange={e=>setNewFilename(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')addFile();}}/><button onClick={addFile}>{tr('إضافة','Add')}</button></div>}<CodeMirror value={files.find(item=>item.name===file)?.content||''} height="420px" extensions={[cpp()]} theme={waslEditor} onChange={change} editable={!locked} basicSetup={{lineNumbers:true,foldGutter:true,highlightActiveLine:true,autocompletion:true,bracketMatching:true}} aria-label="C/C++ code editor"/><div className="code-status"><span>C/C++ · UTF-8 · LTR</span><span>{state?.dirty?tr('المسودة محفوظة محلياً؛ Ctrl+S لحفظ الملفات','Draft saved locally; Ctrl+S saves the files'):tr('تم حفظ ملفات المشروع','Sketch files saved')}</span><span>{tr('عدد الأسطر:', 'Lines:')} {(files.find(item=>item.name===file)?.content||'').split('\n').length}</span></div></div>
    <section className="ide-terminal"><div className="terminal-heading"><div><Terminal size={17}/><h2>{state?.monitoring?tr('مراقب المنفذ التسلسلي','Serial monitor'):tr('نتائج التجميع','Build output')}</h2></div><label><Languages size={15}/><select aria-label={tr('لغة رسائل بيئة البرمجة','Terminal message language')} value={preferences.terminalLanguage} onChange={e=>onPreferences({...preferences,terminalLanguage:e.target.value as 'ar'|'en'}).catch(e=>setError(e.message))}><option value="en">English</option><option value="ar">العربية</option></select></label><button className="icon-button" aria-label={tr('مسح السجل','Clear output')} onClick={()=>run(()=>window.wasl.ide.clearLogs())}><Trash2 size={16}/></button></div><div className="terminal-output" ref={output} role="log" aria-live="off">{state?.logs.length?state.logs.map(log=><div key={log.id} className={`log-${log.kind} ${log.stream==='stderr'?'stderr':''}`} dir={log.kind==='system'&&preferences.terminalLanguage==='ar'?'rtl':'ltr'}>{log.kind==='system'&&<span className="log-time">[{new Date(log.time).toLocaleTimeString('en-GB')}] </span>}{message(log,preferences.terminalLanguage)}</div>):<p dir={preferences.terminalLanguage==='ar'?'rtl':'ltr'}>{preferences.terminalLanguage==='ar'?'جاهز. اختر اللوحة وثبّت حزمة دعمها، ثم اضغط «تجميع».':'Ready. Select a board, install its core, then click Verify.'}</p>}</div><div className="terminal-note">{tr('يغيّر هذا الخيار لغة رسائل وصل فقط. تبقى الشيفرة ورسائل المترجم والأجهزة كما هي.','Language applies to Wasl messages. Compiler/device output stays verbatim; code is never translated.')}</div><div className="serial-toolbar"><label>{tr('سرعة الاتصال','Baud')}<select aria-label={tr('سرعة الاتصال','Baud rate')} value={baud} disabled={locked} onChange={e=>setBaud(Number(e.target.value))}>{[9600,19200,38400,57600,115200,230400].map(value=><option key={value}>{value}</option>)}</select></label><button className="button" disabled={pending||!!state?.busy||(!state?.monitoring&&!port)} onClick={()=>run(()=>state?.monitoring?window.wasl.ide.stop():window.wasl.ide.monitorStart({fqbn,port,baud}))}><Radio size={16}/>{state?.monitoring?tr('إغلاق المراقب التسلسلي','Close monitor'):tr('فتح المراقب التسلسلي','Open monitor')}</button><input aria-label={tr('النص المراد إرساله إلى الجهاز','Serial text')} placeholder={tr('نص لإرساله إلى الجهاز','Text to send to the device')} value={sendText} onChange={e=>setSendText(e.target.value)} disabled={!state?.monitoring} dir="ltr"/><select aria-label={tr('نهاية السطر','Line ending')} value={ending} onChange={e=>setEnding(e.target.value)}><option value="lf">LF</option><option value="crlf">CRLF</option><option value="none">{tr('دون نهاية سطر','None')}</option></select><button className="icon-button" aria-label={tr('إرسال','Send')} disabled={!state?.monitoring} onClick={()=>run(async()=>{await window.wasl.ide.monitorSend({text:sendText,ending});setSendText('');})}><Send size={17}/></button></div></section>
    <div className="ide-footnote"><ShieldNote/>{tr('لا يلزم تسجيل دخول. التحرير يعمل دون إنترنت؛ التجميع والرفع يحتاجان إلى حزمة دعم اللوحة وأدواتها مثبتة محلياً.','No sign-in required. Editing works offline; compiling and uploading require the board core and tools to be installed locally.')}</div>
    {uploadConfirm&&<div className="upload-confirm" role="alertdialog" aria-label={tr('تأكيد رفع البرنامج','Confirm firmware upload')}><div><Upload size={28}/><h2>{tr('رفع البرنامج إلى اللوحة؟','Upload firmware to this board?')}</h2><p>{tr('سيُستبدل البرنامج الحالي على الجهاز الموصول بالمنفذ المحدد.','This replaces the firmware on the device connected to the selected port.')}</p><code dir="ltr">{fqbn} · {port}</code><div><button className="button" onClick={()=>setUploadConfirm(false)}>{tr('إلغاء','Cancel')}</button><button className="button primary" onClick={()=>{setUploadConfirm(false);run(()=>window.wasl.ide.upload({fqbn,port,files}));}}>{tr('رفع الآن','Upload now')}</button></div></div></div>}
  </div>;
}
function CpuIcon(){return <Package size={25}/>;}
function ShieldNote(){return <Check size={15}/>;}
